/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mindfact;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeekkee
 */
public class difficulty extends javax.swing.JFrame {

    /**
     * Creates new form difficulty
     */
    public difficulty() {
        initComponents();
    }

    difficulty(String para) {
        initComponents();
        jLabel2.setText(para);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        easyButton = new javax.swing.JButton();
        mediumButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 200, 90));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 420, 90));

        easyButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        easyButton.setText("EASY");
        easyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyButtonMouseClicked(evt);
            }
        });
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(easyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 320, 70));

        mediumButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        mediumButton.setText("MEDIUM");
        mediumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediumButtonMouseClicked(evt);
            }
        });
        getContentPane().add(mediumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 320, 70));

        hardButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        hardButton.setText("HARD");
        hardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardButtonMouseClicked(evt);
            }
        });
        getContentPane().add(hardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 320, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papebackgrnd.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyButtonMouseClicked
        // TODO add your handling code here:
        String diff1 = "easyquestions";
        String differ1 = "choices";
        Controller control = new Controller();
        
        control.differ = differ1;
        control.diff = diff1;
        
        control.getQuestions();
        dispose();
        
    }//GEN-LAST:event_easyButtonMouseClicked

    private void mediumButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumButtonMouseClicked
        // TODO add your handling code here:
        String diff1 = "mediumquestions";
        String differ1 = "mediumchoices";
        Controller control = new Controller();
        
        control.differ = differ1;
        control.diff = diff1;
        
        control.getQuestions();
        dispose();
    }//GEN-LAST:event_mediumButtonMouseClicked

    private void hardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardButtonMouseClicked
        // TODO add your handling code here:
        String diff1 = "hardquestions";
        String differ1 = "hardchoices";
        Controller control = new Controller();
        
        control.differ = differ1;
        control.diff = diff1;
        
        //OneTimeTask t = new OneTimeTask();
        //Stopwatch g = new Stopwatch();
        //g.run();
        control.getQuestions();
        dispose();
    }//GEN-LAST:event_hardButtonMouseClicked

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new difficulty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mediumButton;
    // End of variables declaration//GEN-END:variables
}
