/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mindfact;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author twinslagemi
 */
public class leaderBoards extends javax.swing.JFrame {

    /**
     * d
     * Creates new form leaderBoards
     */
    public leaderBoards() {
        initComponents();
    }

    public leaderBoards(String questionQ, int secS) {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        name9 = new javax.swing.JLabel();
        name10 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        score6 = new javax.swing.JLabel();
        score7 = new javax.swing.JLabel();
        score8 = new javax.swing.JLabel();
        score9 = new javax.swing.JLabel();
        score10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 33, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("Score");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel2.setText("LEADERBOARDS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 500, 130));

        name1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name1.setText("--------");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        name2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name2.setText("--------");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        name3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name3.setText("--------");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        name4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name4.setText("--------");
        getContentPane().add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        name5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name5.setText("--------");
        getContentPane().add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        name6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name6.setText("--------");
        getContentPane().add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        name7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name7.setText("--------");
        getContentPane().add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        name8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name8.setText("--------");
        getContentPane().add(name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, -1, -1));

        name9.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name9.setText("--------");
        getContentPane().add(name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, -1, -1));

        name10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name10.setText("--------");
        getContentPane().add(name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, -1, -1));

        score1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score1.setText("--------");
        getContentPane().add(score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        score2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score2.setText("--------");
        getContentPane().add(score2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        score3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score3.setText("--------");
        getContentPane().add(score3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        score4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score4.setText("--------");
        getContentPane().add(score4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        score5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score5.setText("--------");
        getContentPane().add(score5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        score6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score6.setText("--------");
        getContentPane().add(score6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        score7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score7.setText("--------");
        getContentPane().add(score7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, -1, -1));

        score8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score8.setText("--------");
        getContentPane().add(score8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, -1, -1));

        score9.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score9.setText("--------");
        getContentPane().add(score9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, -1, -1));

        score10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        score10.setText("--------");
        getContentPane().add(score10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 690, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papebackgrnd.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        Database.getDatabase();
        Controller control = new Controller();

        try {
            int i = 1;
            String sql = "SELECT * FROM userscore ORDER BY score DESC LIMIT 10";
            Database.rs = Database.st.executeQuery(sql);
            while (Database.rs.next()) {
                String user = Database.rs.getString("user");
                String score = Database.rs.getString("score");
                switch (i) {
                    case 1:
                        name1.setText(user);
                        score1.setText(score);
                        i++;
                        break;
                    case 2:
                        name2.setText(user);
                        score2.setText(score);
                        i++;
                        break;
                    case 3:
                        name3.setText(user);
                        score3.setText(score);
                        i++;
                        break;
                    case 4:
                        name4.setText(user);
                        score4.setText(score);
                        i++;
                        break;
                    case 5:
                        name5.setText(user);
                        score5.setText(score);
                        i++;
                        break;
                    case 6:
                        name6.setText(user);
                        score6.setText(score);
                        i++;
                        break;
                    case 7:
                        name7.setText(user);
                        score7.setText(score);
                        i++;
                        break;
                    case 8:
                        name8.setText(user);
                        score8.setText(score);
                        i++;
                        break;
                    case 9:
                        name9.setText(user);
                        score9.setText(score);
                        i++;
                        break;
                    case 10:
                        name10.setText(user);
                        score10.setText(score);
                        i++;
                        break;
                }

            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leaderBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leaderBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leaderBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leaderBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leaderBoards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name10;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    private javax.swing.JLabel name9;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score10;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    private javax.swing.JLabel score6;
    private javax.swing.JLabel score7;
    private javax.swing.JLabel score8;
    private javax.swing.JLabel score9;
    // End of variables declaration//GEN-END:variables
}
